const GET_PLACES_SAGA = 'GET_PLACES_SAGA';
const SET_PLACES = 'SET_PLACES';
const SET_CURRENT_LOCATION = 'SET_CURRENT_LOCATION';

const UPDATE_DB = 'UPDATE_DB';
const CLEAR_DB = 'CLEAR_DB';

const GET_PLACES_FROM_DB = 'GET_PLACES_FROM_DB';
const SET_PATH_NAMES = 'SET_PATH_NAMES';

const SEND_EMAIL = 'SEND_EMAIL';
const DISABLE_MAILCHIMP = 'DISABLE_MAILCHIMP';

const GET_ALL_BLOGS = 'GET_ALL_BLOGS';
const GET_RECENT_BLOGS = 'GET_RECENT_BLOGS';
const SET_BLOGS = 'SET_BLOGS';
const SET_RECENT_BLOGS = 'SET_RECENT_BLOGS';

export {  //eslint-disable-line
	GET_PLACES_SAGA,
	SET_PLACES,
	SET_CURRENT_LOCATION,
	UPDATE_DB,
	CLEAR_DB,
	GET_PLACES_FROM_DB,
	SET_PATH_NAMES,
	SEND_EMAIL,
	DISABLE_MAILCHIMP,

	GET_ALL_BLOGS,
	GET_RECENT_BLOGS,
	SET_BLOGS,
	SET_RECENT_BLOGS
};
